name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: a1
      run: cd gin
    - name: Build
      run: docker build -t gcr.io/crack-atlas-251509/gin:latest .
      
